### ISSUE TITLE
`aux-ps` and others use the wrong readme file

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#362]
|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/169907295-bf2dd567-01d2-46c3-9ff5-ebba245d7074.png)|![image](https://user-images.githubusercontent.com/37152329/169907364-97c4c8c5-7a81-44c2-b7ce-26e8474b3d1c.png)|

**Comment by AbdulrhmnGhanem** [comment]
This is a problem across all [github.com / eez-open](https://github.com/eez-open/modular-psu) multi-projects.

**Comment by kasbah** [comment]
So initially we thought we would make the multi yaml key the "folder". This caused all sorts of annoying things though, including having to deal with slashes in the keys as you see on #359. Later we made people just pretend the yaml key is the name and make everything else explicit, including the `readme:`.  I.e.

```yaml
multi:
  project_name:
    readme: project/folder/readme.md
    gerbers: project/folder/gerbers/
    ...
```

We should probably change it to this, and then it finds it automatically:

```yaml
multi:
  project_name:
    folder: project/folder
``` 

Though if  the rest of the paths are then relative to that folder needs to be decided too. 

We should decide on something and then send PRs to the few projects that need to update their kitspace.yaml afterwards.
