### ISSUE TITLE
`tt_nano_HAT` wrong board showcase

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#420]
https://github.com/vektorious/test_tube_photometer

|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/192525874-65090c03-763b-451c-a347-17f414bd13e7.png)|![image](https://user-images.githubusercontent.com/37152329/192526129-31065038-9964-4b8c-a3a1-bf927ca2383c.png)|

**Comment by AbdulrhmnGhanem** [comment]
@kasbah, what should be the behavior for this?
The paths for the gerbers aren't specified. so it uses the folder with the most gerbers. In v1 the folders to search in are limited by the sub project name.

```yaml
multi:
  tt_nano_HAT_b1:
    summary: Test Tube Photometer Arduino Nano HAT - Version 1
    readme: hardware/pcb/README.md
    bom: hardware/pcb/tt_nano_HAT_b1/1-click-bom.csv
    eda:
      type: kicad
      pcb: hardware/pcb/tt_nano_HAT_b1/tt_nano_HAT_b1.kicad_pcb
  tt_nano_HAT_b2:
    summary: Test Tube Photometer Arduino Nano HAT - Version 2
    readme: hardware/pcb/README.md
    bom: hardware/pcb/tt_nano_HAT_b2/1-click-bom.csv
    eda:
      type: kicad
      pcb: hardware/pcb/tt_nano_HAT_b2/tt_nano_HAT_b2.kicad_pcb
  tt_opt101_module:
    summary: Test Tube Photometer opt101 module.
    readme: hardware/pcb/README.md
    bom: hardware/pcb/tt_opt101_module_b1/tt_opt101_module_b1.kicad_pcb
    eda:
      type: kicad
      pcb: hardware/pcb/tt_opt101_module_b1/tt_opt101_module_b1.kicad_pcb
```
