### ISSUE TITLE
`BeeHive` use project names

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#436]
```yml
multi:
    boards/central-hub:
        summary: the central hub of BeeHive
        readme: README.md
        color: green
        site: https://github.com/isobianin/BeeHive
        bom: hardware/central_hub/1-click-bom.csv
        gerbers: hardware/central_hub/gerber
        eda:
            type: kicad
            pcb: hardware/central_hub/beehive.kicad_pcb
    boards/8-switch-array:
        summary: an array of 8 individually addresseable NPN transistors
        readme: README.md
        color: green
        site: https://github.com/isobianin/BeeHive
        bom: hardware/8_switch_array/1-click-bom.csv
        gerbers: boards/8_switch_array/gerber
        eda:
            type: kicad
            pcb: hardware/8_switch_array/8_switch_array.kicad_pcb
    boards/hp-led-switch:
        summary:  A board to control high powered leds
        readme: README.md
        color: green
        site: https://github.com/isobianin/BeeHive
        bom: hardware/hp_led_switch/1-click-bom.csv
        gerbers: hardware/hp_led_switch/gerber
        eda:
            type: kicad
            pcb: hardware/hp_led_switch/hp_led_switch.kicad_pcb
```
