### ISSUE TITLE
`open-source-rover-shield` wrong board showcase

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#455]
https://github.com/nasa-jpl/open-source-rover

|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/196161756-8d3253b0-4e44-469b-92d2-62266cf8bf80.png)|![image](https://user-images.githubusercontent.com/37152329/196161811-28f2f9ca-b4a8-4e22-a341-995563b37dfa.png)|

**Comment by AbdulrhmnGhanem** [comment]
Actually, this isn't a bug according to the new behavior of the processor.

The `top.svg` and others are generated using gerbers not the kicad files
https://github.com/kitspace/kitspace-v2/blob/9732ed1d486e66594dd07845df00958ab004d088/processor/src/tasks/processGerbers/index.ts#L37-L42

And the `kitspace.yaml` for this project doesn't specify gerbers
```yml
multi:
  open-source-rover-shield:
    summary: Arduino shield for a 6-wheel rover based on the rovers on Mars!
    site: https://opensourcerover.jpl.nasa.gov/
    readme: README.md
    bom: electrical/pcb/arduino_uno_sheild/BOM.csv
    eda:
      type: kicad
      pcb: electrical/pcb/arduino_uno_sheild/Arduino_uno_sheild.kicad_pcb
  open-source-rover-control-board:
    summary: Control board for a 6-wheel rover based on the rovers on Mars!
    site: https://opensourcerover.jpl.nasa.gov/
    readme: README.md
    bom: electrical/pcb/control_board/BOM.csv
    eda:
      type: kicad
      pcb: electrical/pcb/control_board/Control Board.kicad_pcb
```
so it uses
https://github.com/kitspace/kitspace-v2/blob/9732ed1d486e66594dd07845df00958ab004d088/processor/src/tasks/processGerbers/index.ts#L74
which returns the same gerber files for both projects.

I don't know how this even works in v1. the subproject names aren't related to the file paths!
