### ISSUE TITLE
`rrf_rpi_skr_adapter` wrong PCB is rendered

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#565]
https://kitspace.org/boards/gitlab.com/salfter/rrf_rpi_skr_adapter/rrf_rpi_skr_adapter/

|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/220263425-72c873e0-35e1-4cb0-9998-7021fd5c2361.png)|![image](https://user-images.githubusercontent.com/37152329/220263325-83f2ecf5-a1ec-4067-a3d2-8e3bcb53c6c3.png)|

**Comment by AbdulrhmnGhanem** [comment]
Updating the `kitspace.yaml` to the following fixes the issue

```yml
multi:
    rrf_rpi_skr_adapter:
        summary: Raspberry Pi to SKR/SKR Pro Adapter for ReprapFirmware
        color: green
        eda:
            type: kicad
            pcb: rrf_rpi_skr_adapter.kicad_pcb
        bom: 1-click-bom.tsv
        readme: README.md
    rrf_rpi_skr_adapter_panel:
        summary: Raspberry Pi to SKR/SKR Pro Adapter for ReprapFirmware (panel)
        color: green
        eda:
            type: kicad
            pcb: rrf_rpi_skr_adapter.kicad_pcb-panel.kicad_pcb
        bom: 1-click-bom.tsv
        readme: README.md
```
